server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由的匹配
      routes:
        - id: payment_routh           #路由的ID没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供的服务路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/bl/**
            - After=2020-04-04T15:40:40.564+08:00[Asia/Shanghai]
#            - Cookie=username,liujun
#            - Header=X-Request-Id, \d+ #请求头要含有一个X-Request-Id的属性并且值为整数的正则表达式
eureka:
  client:
    #false 表示不向服务注册中心注册自己
    register-with-eureka: true
    #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka