server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/bd2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    #false 表示不向服务注册中心注册自己
    register-with-eureka: true
    #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔 ，单位为秒默认 30
    #lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上线，默认是90秒，超时将剔除服务，（默认Eureka开启保护机制，会保留注册信息）
    #lease-expiration-duration-in-seconds: 90
